module.exports = [
  {
    key: "Dashboard",
    name: "Dashboard",
    link: "/app",
    icon: "dashboard",
    title: true
  },
  {
    key: "HRM",
    name: "HRM",
    icon: "room_preferences",
    child: [
      {
        key: "HRM_Settings",
        name: "HRM Settings",
        title: true,
      },
      {
        key: "Department",
        name: "Department",
        link: "/app/hrm-setting/department",
        icon: "settings_suggest",
      },
      {
        key: "Designation",
        name: "Designation",
        link: "/app/hrm-setting/designation",
        icon: "settings_suggest",
      },
      {
        key: "Leave",
        name: "Leave",
        link: "/app/hrm-setting/leave",
        icon: "settings_suggest",
      },
      {
        key: "Allowance",
        name: "Allowance",
        link: "/app/hrm-setting/allowance",
        icon: "settings_suggest",
      },
      {
        key: "Performance",
        name: "Performance",
        link: "/app/hrm-setting/performance",
        icon: "settings_suggest",
      },
      {
        key: "Compentency Type",
        name: "Compentency Type",
        link: "/app/hrm-setting/compentency-type",
        icon: "settings_suggest",
      },
      {
        key: "Competenies",
        name: "Competenies",
        link: "/app/hrm-setting/competenies",
        icon: "settings_suggest",
      },
      {
        key: "Office Shift",
        name: "Office Shift",
        link: "/app/hrm-setting/office-shift",
        icon: "settings_suggest",
      },
      {
        key: "contact-details",
        name: "contact-details",
        link: "/app/hrm-setting/contact-details",
        icon: "settings_suggest",
      },
      {
        key: "HRM_Settings",
        name: "HRM Settings",
        title: true,
      },
      {
        key: "Department",
        name: "Department",
        link: "/app/hrm-setting/department",
        icon: "settings_suggest",
      },
      {
        key: "Designation",
        name: "Designation",
        link: "/app/hrm-setting/designation",
        icon: "settings_suggest",
      },
      {
        key: "Leave",
        name: "Leave",
        link: "/app/hrm-setting/leave",
        icon: "settings_suggest",
      },
      {
        key: "Allowance",
        name: "Allowance",
        link: "/app/hrm-setting/allowance",
        icon: "settings_suggest",
      },
      {
        key: "Performance",
        name: "Performance",
        link: "/app/hrm-setting/performance",
        icon: "settings_suggest",
      },
      {
        key: "Compentency Type",
        name: "Compentency Type",
        link: "/app/hrm-setting/compentency-type",
        icon: "settings_suggest",
      },
      {
        key: "Competenies",
        name: "Competenies",
        link: "/app/hrm-setting/competenies",
        icon: "settings_suggest",
      },
      {
        key: "Office Shift",
        name: "Office Shift",
        link: "/app/hrm-setting/office-shift",
        icon: "settings_suggest",
      },
      {
        key: "contact-details",
        name: "contact-details",
        link: "/app/hrm-setting/contact-details",
        icon: "settings_suggest",
      },
    ],
  },
  {
    key: "Lead",
    name: "Lead",
    icon: "settings_suggest",
    child: [
      {
        key: "Lead_Settings",
        name: "Lead Settings",
        title: true,
      },
      {
        key: "Lead_Status",
        name: "Lead Status",
        link: "/app/lead/lead-status",
        icon: "settings_suggest",
        badge: "Hot",
      },
      {
        key: "Log_Notes",
        name: "Log Notes",
        link: "/app/lead/log-notes",
        icon: "settings_suggest",
        badge: "Hot",
      },
      {
        key: "Channel",
        name: "Channel",
        link: "/app/lead/Channel",
        icon: "settings_suggest",
        badge: "Hot",
      },
      {
        key: "Lead_Management",
        name: "Lead Management",
        title: true,
      },
      {
        key: "Campaign",
        name: "Campaign",
        icon: "settings_suggest",
        link: "/app/lead/Campaign",
      },
      {
        key: "NewLead",
        name: "New Lead",
        icon: "settings_suggest",
        link: "/app/dashboard/marketing",
      },
      {
        key: "Lead_Members",
        name: "Lead Members",
        icon: "settings_suggest",
        link: "/app/dashboard/crypto",
      },
    ],
  },
  {
    key: "Recruitments",
    name: "Recruitments",
    icon: "settings_suggest",
    child: [
      {
        key: "Custom_Question",
        name: "Custom Question",
        link: "/app/Custom_Question",
        icon: "settings_suggest",
        badge: "Hot",
      },
      {
        key: "Interviewer",
        name: "Interviewer",
        link: "/app/Interviewer",
        icon: "settings_suggest",
        badge: "Hot",
      },
      {
        key: "Job_Create",
        name: "Job Create",
        link: "/app/Job_Create",
        icon: "settings_suggest",
        badge: "Hot",
      },
    ],
  },
];

